baseURL: https://handbook.gitlab.com
languageCode: en-US
locale: en-US
title: The GitLab Handbook

enableRobotsTXT: true
enableGitInfo: true

googleAnalytics: G-41B5X0RBD8

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

params:
  title: The GitLab Handbook
  social:
    twitter: GitLab
  defaultContentLanguage: en
  locale: en-US
  description: Learn more about GitLab and what makes us tick.
  search:
    algolia:
      appId: 3IIMMA8IDY
      apiKey: 71feb3efa6044f78ab6b8a7422e727b7
      indexName: handbook-gitlab
  images:
      - images/gitlab-cover.png
  branch: main
  project: gitlab-com/content-sites/handbook
  repoid: 42817607
  plantuml:
    enable: true
    # svg: true
  mermaid:
    enable: true
  offlineSearch: false
  ui:
    sidebar_menu_compact: false
    sidebar_menu_foldable: true
    sidebar_cache_limit: 1000
    sidebar_menu_truncate: 100
    navbar_logo: true
    footer_about_disable: true
  copyright: "GitLab"
  privacy_policy: https://about.gitlab.com/privacy/
  links:
    user:
      - name: "Slack"
        url: "https://gitlab.slack.com/archives/C81PT2ALD"
        icon: "fab fa-slack"
        desc: "#handbook on Slack"
      - name: "Preferences"
        url: "/preferences/"
        icon: "fa-solid fa-sliders"
        desc: "Handbook Preferences"
      - name: "Repository"
        url: "https://gitlab.com/gitlab-com/content-sites/handbook"
        icon: "fa-solid fa-code-branch"
        desc: "Contribute on GitLab"
    developer: []

staticDir:
        - data
        - static
menu:
  main:
    - weight: -2
      name: GitLab
      url: https://about.gitlab.com/
      pre: '<i class="fab fa-gitlab"></i>'
    - weight: 2
      name: TeamOps
      url: https://about.gitlab.com/teamops
      pre: '<i class="fa-solid fa-arrows-spin"></i>'

mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes: [ "" ]
outputs:
  home: [ "HTML", "REDIRECTS" ]
  section: [ "HTML" ]
outputformats:
  redirects:
    baseName: "_redirects"
    isPlainText: true
    mediaType: "text/netlify"
    notAlternative: true

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: tango
    lineNos: true
    tabWidth: 2
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false

security:
  funcs:
    getenv: [ "^HUGO_", "PERISCOPE_EMBED_API_KEY", "PRODUCT_ANALYTICS_APP_KEY", "PRODUCT_ANALYTICS_HOST" ]

canonifyURLs: true
pluralizeListTitles: false
enableEmoji: true

theme:
- gitlab.com/gitlab-com/content-sites/docsy-gitlab
- github.com/google/docsy

module:
  proxy: https://proxy.golang.org
  hugoVersion:
    extended: true
    min: 0.111
  imports:
  - path: gitlab.com/gitlab-com/content-sites/docsy-gitlab
    disable: false
  - path: github.com/google/docsy
    disable: false
  - path: github.com/google/docsy/dependencies
    disable: false

# Ignore build errors
ignoreErrors:
  # Do not fail to build when we fail to fetch a tweet
  # https://gitlab.com/gitlab-com/content-sites/handbook/-/issues/178
  - error-tweet-failed
